# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# WebHook Mock API
# -----------------------------------------
# START: docker-compose up -d --build --force-recreate
# STOP: docker-compose down -v
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

services:
  mockapi:
    image: ghcr.io/nguyenquy0710/mockapi:latest
    container_name: mockapi
    restart: unless-stopped
    # network_mode: host
    ports:
      - "8081:8081"  # Map cổng host:container (đổi nếu app dùng cổng khác)
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_PROFILES_ACTIVE=default
      - JAVA_OPTS=-Xms256m -Xmx512m -Djava.awt.headless=true # Tùy chỉnh bộ nhớ Java
      - APP_DOMAIN=https://mock-api.quyit.id.vn  # ✅ biến môi trường được Spring Boot hiểu là app.domain
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Lưu trữ database H2 bền vững
    extra_hosts:
      - "host.docker.internal:host-gateway" # Để kết nối đến localhost của host từ container
    deploy:
      resources:
        limits:
          cpus: "0.50" # Giới hạn 80% CPU
          memory: "2G" # Giới hạn 3.2GB RAM (80% của 4GB)
        reservations:
          memory: "256M" # Đảm bảo container có ít nhất 256MB RAM
